"""v2_user_email_digest_fields

Revision ID: a7bca21b9814
Revises: 
Create Date: 2026-09-02 23:55:58.463987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7bca21b9814'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_digest_enabled', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('digest_send_hour', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'digest_send_hour')
    op.drop_column('users', 'email_digest_enabled')
    # ### end Alembic commands ###
